### ISSUE TITLE
Integration with Angular8

### ISSUE THREAD

**Issue by manuelnucci** [nielsboogaard/filepond-plugin-get-file#2]
I'm trying to use te plugin inside an Angular app but I'm not having any success at the moment of displaying the drop zone area. Is there any special attribute I should add in my pondOptions object to enable the functionality and be able to visualize the download option?

This is my object so far:

`pondOptions = {
class: 'my-filepond', labelIdle: 'Arrastre su archivo o haga click <span class="filepond--label-action" tabindex="0">aquí</span> para seleccionarlo',
            required: this.required,
            multiple: this.multipleFiles,
            maxFiles: this.maxFiles,
            allowFileTypeValidation: this.fileTypeValidation,
            acceptedFileTypes: this.mediaTypes.toString(),
            labelFileTypeNotAllowed: 'Tipo de archivo inválido',
            fileValidateTypeLabelExpectedTypes: 'Formatos soportados: ' + this.acceptedFileTypes.toString(),
            allowFileSizeValidation: this.fileSizeValidation,
            maxFileSize: this.maxFileSize,
            labelMaxFileSizeExceeded: 'El archivo es muy grande',
            labelMaxFileSize: 'El tamaño máximo de archivo es ' + this.maxFileSize,
            name: 'filepond',
            allowDownloadByUrl: true
        };`

And this is the HTML associated with it:

> <div [formGroup]="form">
    <file-pond #myPond [options]="pondOptions" [files]="pondFiles" (oninit)="pondHandleInit()"
        (onaddfile)="pondHandleAddFile($event)">
    </file-pond>
</div>

Thanks!

**Comment by nielsboogaard** [comment]
Hi Manuel,

No additional options are required (though you can adjust the label of the icon and allow downloading by url as described in the documentation).

Did you register the get-file plugin to your filePond instance?
`FilePond.registerPlugin(FilePondPluginGetFile);`

**Comment by marcusforsberg** [comment]
I'm also trying to use this with Angular 8. Pretty much the exact same code as @manuelnucci and with the plugin registered on the instance like you're describing, @nielsboogaard.

**Comment by marcusforsberg** [comment]
Ah, derp, you need to include the CSS. 😊 In Angular's case, you can either import in in your `styles.scss`:

```scss
@import '~filepond-plugin-get-file/dist/filepond-plugin-get-file.min.css';
```

Or add it to the `styles` array in `angular.json`:

```json
"styles": [
     "src/styles.scss",
     "../node_modules/filepond-plugin-get-file/dist/filepond-plugin-get-file.min.css"
],
```

I should've known! That said, it might be good to mention including the CSS file in the readme. 😊

**Comment by nielsboogaard** [comment]
Fair point @marcusforsberg :) I've updated the readme instructions with a line about importing the styles.
