### ISSUE TITLE
How to React Implementation 

### ISSUE THREAD

**Issue by dinispeter** [nielsboogaard/filepond-plugin-get-file#3]
Hi, is there any tutorial/documentation on how to implement this plugin into react package?
I followed the installation guide in your readme but could not make it work.
What I did:
npm install filepond-plugin-get-file
import {FilePond, registerPlugin} from "react-filepond";
import FilePondPluginGetFile from 'filepond-plugin-get-file';

registerPlugin( FilePondPluginGetFile);

Is there any working solution or can you tell me what I did wrong? Thanks.

**Comment by MCervenka** [comment]
Hi, I am continuing your project.
At the end the problem was, that there needed to be imported also css file for this plugin.

**Comment by dinispeter** [comment]
Ok.. Thank you very much :)

**Comment by nielsboogaard** [comment]
Sorry for being late with my reaction, but glad to hear it's solved :)

**Comment by techuila** [comment]
Where can I find the css file to be imported?

**Comment by MCervenka** [comment]
Hi.
import 'filepond-plugin-get-file/dist/filepond-plugin-get-file.css';
