### ISSUE TITLE
Filename is not showing, only download icon

### ISSUE THREAD

**Issue by leducvin** [nielsboogaard/filepond-plugin-get-file#6]
Hi,
When I enable the plugin, I can only see the download icon. The filename disappears:

Plugin enabled:
![plugin_enabled](https://user-images.githubusercontent.com/22982038/76094780-2db5b080-5f91-11ea-81fe-7d94cf95cc29.png)

Plugin disabled:
![plugin_disabled](https://user-images.githubusercontent.com/22982038/76094796-34dcbe80-5f91-11ea-88b1-4f979e8d907d.png)

Here is my filepond configuration (note I am loading the file using the "load" endpoint):
```
FilePond.setOptions({
  server: './file',
  allowMultiple: true,
  allowReplace: false,
});

const filepondfiles = [];

files.forEach((id) => {
  filepondfiles.push({
    // the server file reference
    source: id,

    // set type to local to indicate an already uploaded file
    options: {
      type: 'local',
    },
  });
});

FilePond.setOptions({
  files: filepondfiles,
});
```

I followed the instructions in the readme. I am using filepond 4.12.0, same as your demo page, so it's probably safe to rule out a problem with versions. Any idea what might be wrong? Thanks!

**Comment by leducvin** [comment]
Just wanted to add: when doing the initial upload, everything works fine. It's only when loading already-uploaded files in filepond that the filename does not appear.

**Comment by helmi77** [comment]
I have a similar problem, when I specify initial files for the server to load by ID, the label displays the ID instead of the file name.

**Comment by dobrinea** [comment]
Have you resolve issue with - "when I specify initial files for the server to load by ID, the label displays the ID instead of the file name." ?

> I have a similar problem, when I specify initial files for the server to load by ID, the label displays the ID instead of the file name.

**Comment by helmi77** [comment]
No, I stopped using Filepond

**Comment by Zack-Strife** [comment]
As an alternative before the open PR on this is merged, I managed to fix this with a bit of DOM manipulation.
I used the event FilePond:addfile which call a method once the load is done. 
The method has to do the following:  
```
addFile: function (e, file) {
      document.querySelector('.filepond--file-info-main').childNodes[1].data = file.filename
}
```

Maybe not the best fix, but it allow the plugin to works and show the name

**Comment by kamenitxan** [comment]
@Zack-Strife thanks, this works. I just had to edit it, so it supports multiple files. 

```
const pond = FilePond.create();
pond.on('addfile', (error, file) => {
Array.from(document.querySelectorAll('.filepond--file-info-main'))
		.filter(e => {
			return e.textContent === file.serverId
		})
		.forEach(e => e.childNodes[1].data = file.filename)
});
```

**Comment by Superslub** [comment]
@kamenitxan thx. You replace it by performing a text comparison of the element’s textContent.
Here is a piece of code that replaces the text inside the sub-element of the element with the corresponding Id (fileItem.id).

```
onaddfile: async (err, fileItem) => {
            const textNode = document.getElementById('filepond--item-' + fileItem.id)
                                    ?.querySelector('.filepond--file-info-main')
                                    ?.childNodes[1];
            if (textNode && textNode.nodeType === Node.TEXT_NODE) {
                textNode.data = fileItem.filename;
            }
        }
```

BTW:

Try https://github.com/pqina/filepond/issues/596#issuecomment-720963330

Means:
Set  your blobs .name-Property  
AND
set url-property for server

server:{
    url: 'http://192.168.0.100', 
...}
